### PR TITLE
First proposal for teams

### PR DESCRIPTION
**Pull request by fahimaqil**
Please review whether design okay or not. Thanks!
Update: please review the design of the modal
/team -> route

### CODE REVIEW

**Comment by knazran** [comment]
The mobile bio pop is not centered properly

**Comment by fahimaqil** [comment]
> The mobile bio pop is not centered properly

May I know is it vertical or horizontal yang tak center?

**Comment by knazran** [comment]
> > The mobile bio pop is not centered properly
> 
> May I know is it vertical or horizontal yang tak center?

Fixed it already. The footer is overflowing on mobile, hence when you try to center it, it follows the overflowed width hence its off center

**Comment by knazran** [comment]
@fahimaqil 

Few things I want to comment and for you to merge it back to the original /meet-the-team route
- Match the styling of the name and the title with the current TeamMemberCard
- The usage of `nuxt/device` is not necessary. If the goal is to detect device sizes, tailwind has already provided you with the utility already. You can adopt the following pattern:

```html
<div class='hidden md:block'>
    <TeamCardCircle
      :name="name"
      :title="title"
      :img="img"
      :description="description"
    />
  </div>
  <!-- Show in mobile, hide in Desktop -->
  <div class='block md:hidden'>
    <TeamCardCircleMobile
      :name="name"
      :title="title"
      :img="img"
      :description="description"
    />
  </div>
```
- With the above pattern, you can easily merge the 3 TeamCard* files into one. Then move that file under /card component directory.

**Comment by fahimaqil** [comment]
@knazran 
Updated the pages and code. Please review the code. Need confirmation before merging with meet-the-team

**Comment by knazran** [comment]
Can proceed to move to /meet-the-team

**Pull request merged**
